// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-ui/lib/button')['default']
    ElButtonGroup: typeof import('element-ui/lib/button-group')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElCheckboxButton: typeof import('element-ui/lib/checkbox-button')['default']
    ElCheckboxGroup: typeof import('element-ui/lib/checkbox-group')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElDialog: typeof import('element-ui/lib/dialog')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElPagination: typeof import('element-ui/lib/pagination')['default']
    ElRadio: typeof import('element-ui/lib/radio')['default']
    ElRadioButton: typeof import('element-ui/lib/radio-button')['default']
    ElRadioGroup: typeof import('element-ui/lib/radio-group')['default']
    ElRow: typeof import('element-ui/lib/row')['default']
    ElScrollbar: typeof import('element-ui/lib/scrollbar')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTimePicker: typeof import('element-ui/lib/time-picker')['default']
    ElTimeSelect: typeof import('element-ui/lib/time-select')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
