// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElCheckboxButton: typeof import('element-ui/lib/checkbox-button')['default']
    ElCheckboxGroup: typeof import('element-ui/lib/checkbox-group')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElRadio: typeof import('element-ui/lib/radio')['default']
    ElRadioButton: typeof import('element-ui/lib/radio-button')['default']
    ElRadioGroup: typeof import('element-ui/lib/radio-group')['default']
    ElScrollbar: typeof import('element-ui/lib/scrollbar')['default']
    ElTimePicker: typeof import('element-ui/lib/time-picker')['default']
    ElTimeSelect: typeof import('element-ui/lib/time-select')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
